---
- name: prepare system
  hosts: lan
  become: yes

  vars_files:
    - vault

  tasks:
    - name: aurman user
      user:
        name: aurman
        group: wheel

    - name: install yay
      aur:
        name: yay
        use: makepkg
        skip_installed: true

    - name: pacman permission
      template:
        src: 11-aurman
        dest: /etc/sudoers.d/11-aurman
        validate: 'visudo -cf %s'

- name: upgrade core system
  hosts: lan
  become: yes

  vars_files:
    - vault

  tasks:
    - name: pacman upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: yay upgrade
      become_user: aurman
      aur:
        upgrade: yes
        use: yay
        aur_only: yes
